name: 'hohoho'

on:
  workflow_dispatch:
    inputs:
      zoo:
        required: true
        type: string
        default: s

jobs:
  a:
    runs-on: macos-latest
    steps:
      - name: Set FPP based on input
        run: |
          case "${{ github.event.inputs.zoo }}" in
            "s"|"a")
              echo "FPP=zi" >> $GITHUB_ENV
              ;;
            "b")
              echo "FPP=qi" >> $GITHUB_ENV
              ;;
            *)
              echo "FPP=unknown" >> $GITHUB_ENV
              ;;
          esac

      - name: Print FPP
        run: echo "$FPP"
